services:
  - type: web
    name: phishing-detection-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    envVars:
      - key: POETRY_VERSION
        value: "0"